[package]
name = "impl-codec"
version = "0.5.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/paritytech/parity-common"
description = "Parity Codec serialization support for uint and fixed hash."
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.1", default-features = false }

[features]
default = ["std"]
std = ["parity-scale-codec/std"]
